project:
  type: website
  output-dir: docs

website:
  title: "Quarto Website"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Regression Steps"
        href: Regressionanalysis.qmd
      - text: "Git Setup"
        href: GitSetup.qmd
      - text: "Analysis"
        menu:
          - text: "Web Scrapping"
            href: webscrapping.Rmd
          - text: "Wrangling Data"
            href: wranglingdatawithtidyverse.Rmd
          - text: "Exploratory Analysis"
            href: StatisticswithR.qmd
          - text: "Practice"
            href: practice.r
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
